import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Avatar } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";

export default function CallScreen() {
  const { title = "Contact", mode = "video" } = useLocalSearchParams<{ id: string; title?: string; mode?: "voice" | "video" }>(); const [muted, setMuted] = useState(false); const [speaker, setSpeaker] = useState(true); const [video, setVideo] = useState(mode === "video");
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.top}><Text style={styles.callType}>{video ? "VIDEO CALL" : "VOICE CALL"}</Text><Text style={styles.connection}>Call signaling is not configured yet</Text></View><View style={styles.contact}><Avatar profile={{ display_name: title, avatar_path: null }} size={112} /><Text style={styles.name}>{title}</Text><Text style={styles.status}>Ready to call when your call provider is connected</Text></View><View style={styles.controls}><Pressable onPress={() => setMuted((value) => !value)} style={[styles.control, muted && styles.controlActive]}><MaterialIcons name={muted ? "mic-off" : "mic"} size={25} color="#FFFFFF" /><Text style={styles.controlText}>{muted ? "Unmute" : "Mute"}</Text></Pressable><Pressable onPress={() => setSpeaker((value) => !value)} style={[styles.control, speaker && styles.controlActive]}><MaterialIcons name="volume-up" size={25} color="#FFFFFF" /><Text style={styles.controlText}>Speaker</Text></Pressable><Pressable onPress={() => setVideo((value) => !value)} style={[styles.control, video && styles.controlActive]}><MaterialIcons name={video ? "videocam" : "videocam-off"} size={25} color="#FFFFFF" /><Text style={styles.controlText}>Video</Text></Pressable><Pressable onPress={() => router.back()} style={[styles.control, styles.hangup]}><MaterialIcons name="call-end" size={25} color="#FFFFFF" /><Text style={styles.controlText}>End</Text></Pressable></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { backgroundColor: "#10131A", flex: 1, justifyContent: "space-between", padding: 24 }, top: { alignItems: "center", paddingTop: 20 }, callType: { color: "#BFC7FF", fontSize: 12, fontWeight: "900", letterSpacing: 1.5 }, connection: { color: "#9EA9BB", fontSize: 13, marginTop: 7 }, contact: { alignItems: "center", gap: 10 }, name: { color: "#FFFFFF", fontSize: 26, fontWeight: "900", marginTop: 7 }, status: { color: "#B6BFCE", fontSize: 14, textAlign: "center" }, controls: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 16 }, control: { alignItems: "center", backgroundColor: "#30394B", borderRadius: 18, gap: 6, height: 68, justifyContent: "center", width: 68 }, controlActive: { backgroundColor: "#3858E9" }, hangup: { backgroundColor: "#D74343" }, controlText: { color: "#FFFFFF", fontSize: 10, fontWeight: "800" } });
