import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import { ClayPressable, useClayStyles } from "@/components/clay-ui";
import { Avatar } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function CallScreen() {
  const colors = useColors(); const clay = useClayStyles(); const { title = "Contact", mode = "video" } = useLocalSearchParams<{ id: string; title?: string; mode?: "voice" | "video" }>(); const [muted, setMuted] = useState(false); const [speaker, setSpeaker] = useState(true); const [video, setVideo] = useState(mode === "video");
  const control = (active: boolean) => ({ backgroundColor: active ? colors.primary : colors.elevated }); const controlText = (active: boolean) => active ? colors.onPrimary : colors.foreground;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={[styles.page, { backgroundColor: colors.background }]}><View style={styles.top}><Text style={[styles.callType, { color: colors.primary }]}>{video ? "VIDEO CALL" : "VOICE CALL"}</Text><Text style={[styles.connection, { color: colors.muted }]}>Call signaling is not configured yet</Text></View><View style={[styles.contact, clay.elevated, { backgroundColor: colors.elevated }]}><Avatar profile={{ display_name: title, avatar_path: null }} size={112} /><Text style={[styles.name, { color: colors.foreground }]}>{title}</Text><Text style={[styles.status, { color: colors.muted }]}>Ready to call when your call provider is connected</Text></View><View style={styles.controls}><ClayPressable onPress={() => setMuted((value) => !value)} radius={22} style={[styles.control, control(muted)]}><View style={styles.controlContent}><MaterialIcons name={muted ? "mic-off" : "mic"} size={25} color={controlText(muted)} /><Text style={[styles.controlText, { color: controlText(muted) }]}>{muted ? "Unmute" : "Mute"}</Text></View></ClayPressable><ClayPressable onPress={() => setSpeaker((value) => !value)} radius={22} style={[styles.control, control(speaker)]}><View style={styles.controlContent}><MaterialIcons name="volume-up" size={25} color={controlText(speaker)} /><Text style={[styles.controlText, { color: controlText(speaker) }]}>Speaker</Text></View></ClayPressable><ClayPressable onPress={() => setVideo((value) => !value)} radius={22} style={[styles.control, control(video)]}><View style={styles.controlContent}><MaterialIcons name={video ? "videocam" : "videocam-off"} size={25} color={controlText(video)} /><Text style={[styles.controlText, { color: controlText(video) }]}>Video</Text></View></ClayPressable><ClayPressable onPress={() => router.back()} radius={22} style={[styles.control, { backgroundColor: colors.error }]}><View style={styles.controlContent}><MaterialIcons name="call-end" size={25} color={colors.onError} /><Text style={[styles.controlText, { color: colors.onError }]}>End</Text></View></ClayPressable></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, justifyContent: "space-between", padding: 24 }, top: { alignItems: "center", paddingTop: 20 }, callType: { fontSize: 12, fontWeight: "900", letterSpacing: 1.5 }, connection: { fontSize: 13, marginTop: 7 }, contact: { alignItems: "center", borderRadius: 32, gap: 10, padding: 28 }, name: { fontSize: 26, fontWeight: "900", marginTop: 7 }, status: { fontSize: 14, textAlign: "center" }, controls: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 16 }, control: { height: 70, width: 70 }, controlContent: { alignItems: "center", gap: 6, height: 70, justifyContent: "center", width: 70 }, controlText: { fontSize: 10, fontWeight: "800" } });
