import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { CameraView, useCameraPermissions, useMicrophonePermissions } from "expo-camera";
import { router, useLocalSearchParams } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { useRef, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";

export default function CameraCaptureScreen() {
  const colors = useColors(); const { conversationId } = useLocalSearchParams<{ conversationId: string }>(); const [cameraPermission, requestCameraPermission] = useCameraPermissions(); const [microphonePermission, requestMicrophonePermission] = useMicrophonePermissions(); const [facing, setFacing] = useState<"back" | "front">("back"); const [recording, setRecording] = useState(false); const cameraRef = useRef<CameraView>(null);
  const openEditor = (asset: { uri: string; width?: number; height?: number }, kind: "image" | "video") => router.replace({ pathname: "/media-editor", params: { conversationId, uri: asset.uri, kind, name: `${kind}-${Date.now()}.${kind === "image" ? "jpg" : "mp4"}`, mimeType: kind === "image" ? "image/jpeg" : "video/mp4", width: String(asset.width ?? 0), height: String(asset.height ?? 0) } } as never);
  const capture = async () => { if (!cameraRef.current) return; try { if (recording) { cameraRef.current.stopRecording(); return; } const photo = await cameraRef.current.takePictureAsync({ quality: 0.88, skipProcessing: false }); if (photo) openEditor(photo, "image"); } catch (error) { Alert.alert("Camera unavailable", error instanceof Error ? error.message : "Unable to take a photo."); } };
  const captureVideo = async () => { if (!cameraRef.current) return; try { if (!microphonePermission?.granted) { const permission = await requestMicrophonePermission(); if (!permission.granted) return; } setRecording(true); const video = await cameraRef.current.recordAsync({ maxDuration: 60 }); setRecording(false); if (video) openEditor(video, "video"); } catch (error) { setRecording(false); Alert.alert("Camera unavailable", error instanceof Error ? error.message : "Unable to record a video."); } };
  if (!cameraPermission) return <View />;
  if (!cameraPermission.granted) return <View style={[styles.permission, { backgroundColor: colors.background }]}><MaterialIcons color={colors.primary} name="photo-camera" size={44} /><Text style={[styles.permissionTitle, { color: colors.foreground }]}>Camera access</Text><Text style={[styles.permissionCopy, { color: colors.muted }]}>Allow camera access to capture photos and videos for your conversation.</Text><Pressable onPress={() => void requestCameraPermission()} style={[styles.allow, { backgroundColor: colors.primary }]}><Text style={[styles.allowText, { color: colors.onPrimary }]}>Allow camera</Text></Pressable></View>;
  return <View style={styles.page}><StatusBar backgroundColor="#000000" style="light" /><CameraView facing={facing} ref={cameraRef} style={styles.camera}><View style={styles.top}><Pressable accessibilityLabel="Close camera" onPress={() => router.back()} style={styles.icon}><MaterialIcons color={colors.onPrimary} name="close" size={27} /></Pressable><Pressable accessibilityLabel="Switch camera" onPress={() => setFacing((value) => value === "back" ? "front" : "back")} style={styles.icon}><MaterialIcons color={colors.onPrimary} name="flip-camera-android" size={26} /></Pressable></View><View style={styles.bottom}><Pressable accessibilityLabel="Record video" disabled={recording} onPress={() => void captureVideo()} style={[styles.modeButton, { backgroundColor: colors.error }]}>{recording ? <ActivityIndicator color={colors.onError} /> : <MaterialIcons color={colors.onError} name="videocam" size={22} />}</Pressable><Pressable accessibilityLabel={recording ? "Stop recording" : "Take photo"} onPress={() => void capture()} style={[styles.shutter, { borderColor: colors.onPrimary }, recording && { borderColor: colors.error }]}><View style={[styles.shutterInner, { backgroundColor: colors.onPrimary }, recording && { backgroundColor: colors.error, borderRadius: 7, height: 28, width: 28 }]} /></Pressable><View style={styles.modeButton} /></View></CameraView></View>;
}
const styles = StyleSheet.create({ page: { backgroundColor: "#000000", flex: 1 }, camera: { flex: 1 }, top: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 20, paddingTop: 56 }, icon: { alignItems: "center", backgroundColor: "rgba(0,0,0,0.35)", borderRadius: 22, height: 44, justifyContent: "center", width: 44 }, bottom: { alignItems: "center", bottom: 38, flexDirection: "row", justifyContent: "space-between", left: 0, paddingHorizontal: 42, position: "absolute", right: 0 }, modeButton: { alignItems: "center", borderRadius: 22, height: 44, justifyContent: "center", width: 44 }, shutter: { alignItems: "center", borderRadius: 34, borderWidth: 4, height: 68, justifyContent: "center", width: 68 }, shutterInner: { borderRadius: 28, height: 54, width: 54 }, permission: { alignItems: "center", flex: 1, gap: 14, justifyContent: "center", padding: 28 }, permissionTitle: { fontSize: 22, fontWeight: "900" }, permissionCopy: { fontSize: 15, lineHeight: 22, textAlign: "center" }, allow: { borderRadius: 14, marginTop: 8, paddingHorizontal: 18, paddingVertical: 13 }, allowText: { fontSize: 15, fontWeight: "900" } });
