import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, PrimaryButton, ScreenHeader } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { createGroupConversation, listFriends } from "@/lib/chat-api";
import type { Profile } from "@/shared/chat-types";

export default function CreateGroupScreen() {
  const colors = useColors();
  const [name, setName] = useState(""); const [friends, setFriends] = useState<Profile[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [creating, setCreating] = useState(false);
  useEffect(() => { listFriends().then((result) => { setLoading(false); if (result.error) setError(result.error.message); else setFriends(result.data); }); }, []);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((member) => member !== id) : [...current, id]);
  const create = async () => { if (!name.trim()) return setError("Give your group a name."); setCreating(true); setError(null); const result = await createGroupConversation(name.trim(), selected); setCreating(false); if (result.error) return setError(result.error.message); router.replace({ pathname: "/conversation/[id]", params: { id: result.data, title: name.trim(), kind: "group" } } as never); };
  return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]}><ScreenHeader title="New group" onBack={() => router.back()} /><View style={styles.form}><Text style={[styles.label, { color: colors.foreground }]}>Group name</Text><TextInput maxLength={80} onChangeText={setName} placeholder="Weekend plans" placeholderTextColor={colors.subtle} style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.foreground }]} value={name} /><Text style={[styles.helper, { color: colors.muted }]}>Invite members now, or add them later if you have permission.</Text></View><View style={styles.memberHeader}><Text style={[styles.label, { color: colors.foreground }]}>Invite friends</Text><Text style={[styles.selection, { color: colors.primary }]}>{selected.length} selected</Text></View>{loading ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : <FlatList data={friends} contentContainerStyle={styles.list} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={[styles.empty, { color: colors.muted }]}>{error ?? "You can create a group now and invite people later."}</Text>} renderItem={({ item }) => <Pressable onPress={() => toggle(item.id)} style={({ pressed }) => [styles.friend, { borderBottomColor: colors.border }, pressed && styles.pressed]}><Avatar profile={item} size={44} /><View style={styles.friendText}><Text style={[styles.friendName, { color: colors.foreground }]}>{item.display_name}</Text><Text style={[styles.friendHandle, { color: colors.muted }]}>@{item.username}</Text></View><View style={[styles.check, { borderColor: colors.border }, selected.includes(item.id) && { backgroundColor: colors.primary, borderColor: colors.primary }]}>{selected.includes(item.id) ? <MaterialIcons name="check" color={colors.onPrimary} size={18} /> : null}</View></Pressable>} />}{error && friends.length ? <Text style={[styles.error, { color: colors.error }]}>{error}</Text> : null}<View style={[styles.footer, { backgroundColor: colors.elevated, borderTopColor: colors.border }]}><PrimaryButton label="Create group" loading={creating} onPress={create} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ form: { gap: 7, paddingTop: 16 }, label: { fontSize: 14, fontWeight: "800" }, input: { borderRadius: 14, borderWidth: 1, fontSize: 16, minHeight: 52, paddingHorizontal: 15 }, helper: { fontSize: 12, lineHeight: 17 }, memberHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 22 }, selection: { fontSize: 13, fontWeight: "800" }, loader: { marginTop: 35 }, list: { paddingBottom: 80, paddingTop: 10 }, empty: { lineHeight: 21, paddingTop: 25, textAlign: "center" }, friend: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 11, minHeight: 64, paddingVertical: 9 }, friendText: { flex: 1 }, friendName: { fontSize: 15, fontWeight: "800" }, friendHandle: { fontSize: 12, marginTop: 2 }, check: { alignItems: "center", borderRadius: 11, borderWidth: 1.5, height: 22, justifyContent: "center", width: 22 }, footer: { borderTopWidth: 1, bottom: 0, left: 0, padding: 14, position: "absolute", right: 0 }, error: { marginTop: 10, textAlign: "center" }, pressed: { opacity: 0.72 } });
