import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { useClayStyles } from "@/components/clay-ui";
import { Avatar, FormField, FullScreenLoader, PrimaryButton, ScreenHeader } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { updateProfile, uploadAvatar } from "@/lib/chat-api";
import { useChatAuth } from "@/providers/chat-auth-provider";

export default function EditProfileScreen() {
  const colors = useColors(); const clay = useClayStyles();
  const { profile, updateCachedProfile } = useChatAuth();
  const [displayName, setDisplayName] = useState(""); const [username, setUsername] = useState(""); const [bio, setBio] = useState(""); const [avatarUri, setAvatarUri] = useState<string | null>(null); const [avatarMimeType, setAvatarMimeType] = useState("image/jpeg"); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (profile) { setDisplayName(profile.display_name); setUsername(profile.username); setBio(profile.bio ?? ""); } }, [profile]);
  const changed = useMemo(() => Boolean(profile && (displayName !== profile.display_name || username !== profile.username || bio !== (profile.bio ?? "") || avatarUri)), [profile, displayName, username, bio, avatarUri]);
  const close = () => { if (changed) Alert.alert("Discard changes?", "Your changes haven't been saved.", [{ text: "Keep editing", style: "cancel" }, { text: "Discard", style: "destructive", onPress: () => router.back() }]); else router.back(); };
  const chooseAvatar = async () => { setError(null); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1, 1], quality: 0.85 }); if (!result.canceled) { const selected = result.assets[0]; setAvatarUri(selected.uri); setAvatarMimeType(selected.mimeType ?? "image/jpeg"); } };
  const save = async () => { if (!profile || !changed) return; setSaving(true); setError(null); const updated = await updateProfile({ display_name: displayName, username, bio }); if (updated.error) { setSaving(false); return setError(updated.error.message); } let finalProfile = updated.data; if (avatarUri) { const avatar = await uploadAvatar(avatarUri, avatarMimeType); if (avatar.error) { setSaving(false); return setError(`Profile details were saved, but the avatar upload failed: ${avatar.error.message}`); } finalProfile = avatar.data; } updateCachedProfile(finalProfile); setSaving(false); router.back(); };
  if (!profile) return <FullScreenLoader label="Loading your profile" />;
  return <ScreenContainer className="px-6" edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={styles.grow}><ScreenHeader title="Edit profile" onBack={close} /><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.avatarBlock}><Pressable accessibilityLabel="Change avatar" onPress={chooseAvatar} style={({ pressed }) => [styles.avatarPressable, clay.raised, { backgroundColor: colors.elevated }, pressed && styles.pressed]}>{avatarUri ? <Image source={avatarUri} contentFit="cover" style={styles.avatarPreview} /> : <Avatar profile={profile} size={92} />}<View style={[styles.cameraBadge, clay.raised, { backgroundColor: colors.primary }]}><MaterialIcons name="photo-camera" color={colors.onPrimary} size={16} /></View></Pressable><Text onPress={chooseAvatar} style={[styles.changeAvatar, { color: colors.primary }]}>Change avatar</Text><Text style={[styles.avatarHint, { color: colors.muted }]}>Choose a square image, then save to upload it.</Text></View><View style={styles.form}><FormField label="Display name" onChangeText={setDisplayName} value={displayName} /><FormField label="Username" autoCapitalize="none" onChangeText={setUsername} value={username} /><FormField label="Description" multiline numberOfLines={4} onChangeText={setBio} placeholder="Tell people a little about yourself" style={[styles.bioInput]} textAlignVertical="top" value={bio} />{error ? <Text accessibilityRole="alert" style={[styles.error, clay.sunken, { backgroundColor: colors.error + "18", color: colors.error }]}>{error}</Text> : null}<PrimaryButton label={avatarUri ? "Save changes & upload avatar" : "Save changes"} disabled={!changed} loading={saving} onPress={save} /></View></ScrollView></KeyboardAvoidingView></ScreenContainer>;
}
const styles = StyleSheet.create({ grow: { flex: 1 }, content: { gap: 24, paddingBottom: 40, paddingTop: 16 }, avatarBlock: { alignItems: "center", gap: 7 }, avatarPressable: { borderRadius: 52, padding: 5, position: "relative" }, avatarPreview: { borderRadius: 46, height: 92, width: 92 }, cameraBadge: { alignItems: "center", borderRadius: 16, bottom: -3, height: 32, justifyContent: "center", position: "absolute", right: -3, width: 32 }, changeAvatar: { fontSize: 15, fontWeight: "800", marginTop: 4 }, avatarHint: { fontSize: 12 }, form: { gap: 16 }, bioInput: { minHeight: 114, paddingTop: 14 }, error: { borderRadius: 18, fontSize: 14, lineHeight: 20, padding: 13 }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] } });
