import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, InlineIdentity, ScreenHeader } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { searchProfiles } from "@/lib/chat-api";
import { useChatAuth } from "@/providers/chat-auth-provider";
import type { Profile } from "@/shared/chat-types";

export default function FindPeopleScreen() {
  const { profile: currentProfile } = useChatAuth();
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Profile[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const search = async (value = query) => { setQuery(value); if (!value.trim()) { setResults([]); setError(null); return; } setLoading(true); setError(null); const result = await searchProfiles(value); setLoading(false); if (result.error) return setError(result.error.message); setResults(result.data.filter((candidate) => candidate.id !== currentProfile?.id)); };
  return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]}><ScreenHeader title="Find people" onBack={() => router.back()} /><View style={styles.search}><MaterialIcons name="search" size={21} color="#687086" /><TextInput autoCapitalize="none" autoCorrect={false} onChangeText={(value) => void search(value)} placeholder="Name or username" placeholderTextColor="#8A93A7" style={styles.input} value={query} /></View>{loading ? <View style={styles.loader}><ActivityIndicator color="#3858E9" /></View> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<FlatList contentContainerStyle={results.length ? styles.list : styles.emptyList} data={results} keyboardShouldPersistTaps="handled" keyExtractor={(item) => item.id} ListEmptyComponent={!loading && query.trim() ? <Text style={styles.empty}>No people found. Try another name or username.</Text> : <Text style={styles.empty}>Search Chat by display name or username.</Text>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/profile/${item.id}` as never)} style={({ pressed }) => [styles.result, pressed && styles.pressed]}><Avatar profile={item} size={48} /><View style={styles.resultText}><InlineIdentity label={item.display_name} verified={item.verified} textStyle={styles.name} /><Text style={styles.username}>@{item.username}</Text>{item.bio ? <Text numberOfLines={1} style={styles.bio}>{item.bio}</Text> : null}</View><MaterialIcons name="chevron-right" size={22} color="#98A1B3" /></Pressable>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ search: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#DCE1ED", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 10, marginTop: 12, minHeight: 52, paddingHorizontal: 14 }, input: { color: "#171B25", flex: 1, fontSize: 16 }, list: { paddingBottom: 30, paddingTop: 14 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 80 }, empty: { color: "#7C8497", fontSize: 15, lineHeight: 22, paddingHorizontal: 30, textAlign: "center" }, loader: { marginTop: 14 }, error: { color: "#B52D2D", marginTop: 12 }, result: { alignItems: "center", backgroundColor: "#FFFFFF", borderBottomColor: "#EEF0F5", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 12, minHeight: 74, paddingHorizontal: 3 }, resultText: { flex: 1 }, name: { color: "#171B25", fontSize: 16, fontWeight: "800" }, username: { color: "#687086", fontSize: 13, marginTop: 2 }, bio: { color: "#7C8497", fontSize: 12, marginTop: 3 }, pressed: { opacity: 0.72 } });
