import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useState } from "react";
import { useFocusEffect } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";

import { Avatar, BadgeRow, FullScreenLoader, InlineIdentity, PrimaryButton, ScreenHeader, SecondaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { blockUser, createDirectConversation, getFriendshipRelationship, reportUser, sendFriendRequest, type FriendshipRelationship } from "@/lib/chat-api";
import { supabase } from "@/lib/supabase";
import { useChatAuth } from "@/providers/chat-auth-provider";
import type { Profile } from "@/shared/chat-types";

export default function ProfileScreen() {
  const colors = useColors(); const { id } = useLocalSearchParams<{ id: string }>(); const { profile: ownProfile } = useChatAuth(); const [profile, setProfile] = useState<Profile | null>(null); const [relationship, setRelationship] = useState<FriendshipRelationship>("none"); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  const refresh = useCallback(async () => { let mounted = true; setLoading(true); const { data, error: queryError } = await supabase.from("profiles").select("*").eq("id", id).single(); if (!mounted) return; const nextProfile = (data as Profile | null) ?? null; setProfile(nextProfile); if (queryError || !nextProfile) { setError(queryError?.message ?? null); setLoading(false); return; } if (ownProfile?.id !== nextProfile.id) { const relation = await getFriendshipRelationship(nextProfile.id); if (!mounted) return; if (relation.error) setError(relation.error.message); else { setRelationship(relation.data); setError(null); } } else { setRelationship("none"); setError(null); } setLoading(false); return () => { mounted = false; }; }, [id, ownProfile?.id]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  if (loading) return <FullScreenLoader label="Opening profile" />;
  if (!profile) return <ScreenContainer className="px-6" edges={["top", "bottom", "left", "right"]}><ScreenHeader title="Profile" onBack={() => router.back()} /><View style={styles.unavailable}><Text style={[styles.unavailableTitle, { color: colors.foreground }]}>Profile unavailable</Text><Text style={[styles.unavailableText, { color: colors.muted }]}>{error ?? "This profile may no longer be available."}</Text></View></ScreenContainer>;
  const isOwnProfile = ownProfile?.id === profile.id;
  const run = async (action: () => Promise<{ error: Error | null }>, success: string) => { setWorking(true); const result = await action(); setWorking(false); if (result.error) Alert.alert("Unable to complete action", result.error.message); else { Alert.alert("Done", success); void refresh(); } };
  const startMessage = async () => { setWorking(true); const result = await createDirectConversation(profile.id); setWorking(false); if (result.error) return Alert.alert("Unable to start conversation", result.error.message); router.push({ pathname: "/conversation/[id]", params: { id: result.data, title: profile.display_name, kind: "direct", verified: profile.verified ? "true" : "false" } } as never); };
  const report = () => Alert.prompt?.("Report account", "Briefly describe the issue.", (description) => void run(() => reportUser(profile.id, "User report", description), "Your report has been submitted.")) ?? Alert.alert("Report account", "Reports are sent securely. Continue?", [{ text: "Cancel", style: "cancel" }, { text: "Report", style: "destructive", onPress: () => void run(() => reportUser(profile.id, "User report"), "Your report has been submitted.") }]);
  const relationshipAction = relationship === "friends" ? <SecondaryButton disabled icon="check-circle" label="Friends" onPress={() => undefined} /> : relationship === "outgoing_pending" ? <SecondaryButton disabled icon="schedule" label="Request pending" onPress={() => undefined} /> : relationship === "incoming_pending" ? <SecondaryButton disabled icon="person-add" label="Friend request received" onPress={() => undefined} /> : <SecondaryButton icon="person-add" label="Add friend" onPress={() => void run(() => sendFriendRequest(profile.id), "Friend request sent.")} />;
  return <ScreenContainer className="px-6" edges={["top", "bottom", "left", "right"]}><ScreenHeader title={isOwnProfile ? "My profile" : "Profile"} onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Avatar profile={profile} size={96} /><Text style={[styles.name, { color: colors.foreground }]}>{profile.display_name}</Text><View style={styles.identityLine}><InlineIdentity label={`@${profile.username}`} verified={profile.verified} textStyle={[styles.username, { color: colors.muted }]} /><BadgeRow badges={profile.badges} /></View>{profile.bio ? <Text style={[styles.bio, { color: colors.muted }]}>{profile.bio}</Text> : null}<Text style={[styles.status, { backgroundColor: colors.success + "20", color: colors.success }]}>{profile.status}</Text></View>{isOwnProfile ? <View style={styles.actions}><PrimaryButton icon="edit" label="Edit profile" onPress={() => router.push("/edit-profile" as never)} /><SecondaryButton icon="settings" label="Account settings" onPress={() => router.push("/(tabs)/account" as never)} /></View> : <View style={styles.actions}><PrimaryButton icon="chat-bubble-outline" label="Message" loading={working} onPress={() => void startMessage()} />{relationshipAction}<SecondaryButton icon="block" label="Block user" destructive onPress={() => Alert.alert("Block this user?", "They will no longer be able to contact you directly.", [{ text: "Cancel", style: "cancel" }, { text: "Block", style: "destructive", onPress: () => void run(() => blockUser(profile.id), "This user is now blocked.") }])} /><SecondaryButton icon="flag" label="Report user" destructive onPress={report} /></View>}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 22, paddingBottom: 40, paddingTop: 28 }, hero: { alignItems: "center" }, name: { fontSize: 26, fontWeight: "900", letterSpacing: -0.5, marginTop: 14 }, identityLine: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "center", marginTop: 5 }, username: { fontSize: 15, fontWeight: "700" }, bio: { fontSize: 15, lineHeight: 23, marginTop: 15, textAlign: "center" }, status: { borderRadius: 10, fontSize: 12, fontWeight: "800", marginTop: 15, paddingHorizontal: 9, paddingVertical: 5 }, actions: { gap: 10 }, unavailable: { alignItems: "center", flex: 1, justifyContent: "center", paddingHorizontal: 28 }, unavailableTitle: { fontSize: 20, fontWeight: "800" }, unavailableText: { lineHeight: 21, marginTop: 8, textAlign: "center" } });
