import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { RecordingPresets, requestRecordingPermissionsAsync, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from "expo-audio";
import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, StyleSheet, Text, View } from "react-native";

import { ClayPressable } from "@/components/clay-ui";
import { useColors } from "@/hooks/use-colors";
import type { PendingAttachment } from "@/shared/chat-types";

function formatDuration(milliseconds: number) { const seconds = Math.floor(milliseconds / 1000); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }

export function VoiceRecorderButton({ disabled, onRecorded }: { disabled?: boolean; onRecorded: (attachment: PendingAttachment) => Promise<void> | void }) {
  const colors = useColors(); const recorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY); const state = useAudioRecorderState(recorder); const [submitting, setSubmitting] = useState(false); const waveform = useMemo(() => [10, 16, 24, 14, 29, 19, 32, 17, 26, 12, 30, 21], []);
  const toggle = async () => { try { if (state.isRecording) { await recorder.stop(); if (!recorder.uri) throw new Error("The voice message could not be saved."); setSubmitting(true); await onRecorded({ uri: recorder.uri, name: `voice-${Date.now()}.m4a`, mimeType: "audio/m4a", size: 1, kind: "audio", durationMs: Math.max(1000, state.durationMillis ?? 1000) }); setSubmitting(false); return; } const permission = await requestRecordingPermissionsAsync(); if (!permission.granted) return Alert.alert("Microphone unavailable", "Allow microphone access to record a voice message."); await setAudioModeAsync({ playsInSilentMode: true, allowsRecording: true }); await recorder.prepareToRecordAsync(); recorder.record(); } catch (error) { setSubmitting(false); Alert.alert("Voice message unavailable", error instanceof Error ? error.message : "Please try again."); } };
  if (state.isRecording) return <ClayPressable accessibilityLabel="Stop and send voice recording" onPress={() => void toggle()} radius={22} style={[styles.recordingBar, { backgroundColor: colors.error + "22" }]}><View style={styles.recordingContent}><View style={[styles.liveDot, { backgroundColor: colors.error }]} /><View style={styles.waveform}>{waveform.map((height, index) => <View key={index} style={[styles.waveBar, { backgroundColor: colors.error, height }]} />)}</View><Text style={[styles.duration, { color: colors.error }]}>{formatDuration(state.durationMillis ?? 0)}</Text><View style={[styles.stop, { backgroundColor: colors.error }]}><MaterialIcons color={colors.onError} name="stop" size={16} /></View></View></ClayPressable>;
  return <ClayPressable accessibilityLabel="Record voice message" disabled={disabled || submitting} onPress={() => void toggle()} radius={19} style={[styles.button, { backgroundColor: colors.accentSoft }, (disabled || submitting) && styles.disabled]}><View style={styles.buttonContent}>{submitting ? <ActivityIndicator color={colors.primary} size="small" /> : <MaterialIcons name="mic-none" color={colors.primary} size={22} />}</View></ClayPressable>;
}
const styles = StyleSheet.create({ button: { height: 40, width: 40 }, buttonContent: { alignItems: "center", height: 40, justifyContent: "center", width: 40 }, recordingBar: { flex: 1, height: 44, paddingHorizontal: 10 }, recordingContent: { alignItems: "center", flexDirection: "row", gap: 8, height: 44 }, liveDot: { borderRadius: 4, height: 8, width: 8 }, waveform: { alignItems: "center", flex: 1, flexDirection: "row", gap: 2, height: 34 }, waveBar: { borderRadius: 3, width: 2 }, duration: { fontSize: 12, fontVariant: ["tabular-nums"], fontWeight: "900" }, stop: { alignItems: "center", borderRadius: 13, height: 26, justifyContent: "center", width: 26 }, disabled: { opacity: 0.5 } });
