import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Avatar, FullScreenLoader, InlineIdentity, PrimaryButton, ScreenHeader } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { getGroupDetails, removeGroupMember, setGroupMemberRole } from "@/lib/chat-api";
import { useChatAuth } from "@/providers/chat-auth-provider";

type GroupDetails = NonNullable<Awaited<ReturnType<typeof getGroupDetails>>["data"]>;

export default function GroupDetailsScreen() {
  const colors = useColors();
  const { id: conversationId } = useLocalSearchParams<{ id: string }>(); const { profile } = useChatAuth(); const [group, setGroup] = useState<GroupDetails | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const result = await getGroupDetails(conversationId); setLoading(false); if (result.error) return setError(result.error.message); setGroup(result.data); setError(null); }, [conversationId]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <FullScreenLoader label="Loading group" />;
  if (!group) return <ScreenContainer className="px-6" edges={["top", "bottom", "left", "right"]}><ScreenHeader title="Group" onBack={() => router.back()} /><View style={styles.errorWrap}><Text style={[styles.error, { color: colors.error }]}>{error ?? "Group details are unavailable."}</Text><PrimaryButton label="Retry" onPress={() => void load()} /></View></ScreenContainer>;
  const ownMember = group.members.find((member) => member.user_id === profile?.id); const canInvite = group.created_by === profile?.id || Boolean(group.roles.find((role) => role.id === ownMember?.role_id)?.can_invite); const canManageRoles = group.created_by === profile?.id || Boolean(group.roles.find((role) => role.id === ownMember?.role_id)?.can_manage_roles); const canRemove = group.created_by === profile?.id || Boolean(group.roles.find((role) => role.id === ownMember?.role_id)?.can_remove_members);
  const memberAction = (member: GroupDetails["members"][number]) => { if (member.user_id === group.created_by) return; const actions: any[] = []; if (canManageRoles) group.roles.filter((role) => group.created_by === profile?.id || role.rank < (ownMember?.role?.rank ?? -1)).forEach((role) => actions.push({ text: `Make ${role.name}`, onPress: async () => { const result = await setGroupMemberRole(group.id, member.user_id, role.id); if (result.error) Alert.alert("Role not updated", result.error.message); else void load(); } })); if (canRemove || member.user_id === profile?.id) actions.push({ text: member.user_id === profile?.id ? "Leave group" : "Remove member", style: "destructive", onPress: async () => { const result = await removeGroupMember(group.id, member.user_id); if (result.error) Alert.alert("Action unavailable", result.error.message); else router.back(); } }); actions.push({ text: "Cancel", style: "cancel" }); Alert.alert(member.profile.display_name, "Choose an allowed action.", actions); };
  return <ScreenContainer className="px-5" edges={["top", "bottom", "left", "right"]}><ScreenHeader title="Group details" onBack={() => router.back()} /><View style={styles.hero}><View style={[styles.heroIcon, { backgroundColor: colors.accentSoft }]}><MaterialIcons name="groups" size={32} color={colors.primary} /></View><Text style={[styles.name, { color: colors.foreground }]}>{group.name}</Text><Text style={[styles.caption, { color: colors.muted }]}>{group.members.length} member{group.members.length === 1 ? "" : "s"}</Text>{canInvite ? <Pressable onPress={() => router.push(`/group-invite/${conversationId}` as never)} style={({ pressed }) => [styles.invite, { backgroundColor: colors.accentSoft, borderColor: colors.border }, pressed && styles.pressed]}><MaterialIcons name="person-add" size={18} color={colors.primary} /><Text style={[styles.inviteText, { color: colors.primary }]}>Invite people</Text></Pressable> : null}</View><Text style={[styles.section, { color: colors.subtle }]}>MEMBERS</Text><FlatList data={group.members.sort((a, b) => (b.role?.rank ?? -1) - (a.role?.rank ?? -1))} contentContainerStyle={styles.list} keyExtractor={(item) => item.user_id} renderItem={({ item }) => <View style={[styles.member, { borderBottomColor: colors.border }]}><Pressable onPress={() => router.push(`/profile/${item.user_id}` as never)} style={({ pressed }) => [styles.memberProfile, pressed && styles.pressed]}><Avatar profile={item.profile} size={45} /><View style={styles.memberText}><InlineIdentity label={item.profile.display_name} verified={item.profile.verified} textStyle={[styles.memberName, { color: colors.foreground }]} /><Text style={[styles.memberUsername, { color: colors.muted }]}>@{item.profile.username}</Text></View></Pressable><View style={[styles.role, { backgroundColor: colors.accentSoft, borderColor: colors.border }]}><Text style={[styles.roleText, { color: colors.foreground }]}>{item.user_id === group.created_by ? "Owner" : item.role?.name ?? "Member"}</Text></View>{(canManageRoles || canRemove || item.user_id === profile?.id) && item.user_id !== group.created_by ? <Pressable accessibilityLabel={`Manage ${item.profile.display_name}`} onPress={() => memberAction(item)} style={styles.memberMenu}><MaterialIcons name="more-horiz" size={20} color={colors.foreground} /></Pressable> : null}</View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ hero: { alignItems: "center", gap: 5, paddingBottom: 18, paddingTop: 18 }, heroIcon: { alignItems: "center", borderRadius: 26, height: 60, justifyContent: "center", width: 60 }, name: { fontSize: 22, fontWeight: "900", marginTop: 6 }, caption: { fontSize: 13 }, invite: { alignItems: "center", borderRadius: 11, borderWidth: 1, flexDirection: "row", gap: 7, marginTop: 10, paddingHorizontal: 12, paddingVertical: 9 }, inviteText: { fontSize: 13, fontWeight: "900" }, section: { fontSize: 11, fontWeight: "900", letterSpacing: 1, marginBottom: 4 }, list: { paddingBottom: 20 }, member: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 9, minHeight: 66 }, memberProfile: { alignItems: "center", flex: 1, flexDirection: "row", gap: 11, minHeight: 65 }, memberText: { flex: 1 }, memberName: { fontSize: 15, fontWeight: "800" }, memberUsername: { fontSize: 12, marginTop: 2 }, role: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 4 }, roleText: { fontSize: 11, fontWeight: "800" }, memberMenu: { alignItems: "center", height: 42, justifyContent: "center", width: 32 }, pressed: { opacity: 0.72 }, errorWrap: { flex: 1, gap: 15, justifyContent: "center" }, error: { lineHeight: 21, textAlign: "center" } });
