import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Avatar, BadgeRow, FullScreenLoader, InlineIdentity, SecondaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useChatAuth } from "@/providers/chat-auth-provider";

function SettingsRow({ icon, label, description, onPress, destructive = false }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; description?: string; onPress: () => void; destructive?: boolean }) {
  const colors = useColors();
  const tone = destructive ? colors.error : colors.primary;
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, { borderBottomColor: colors.border }, pressed && { backgroundColor: colors.accentSoft }]}><View style={[styles.rowIcon, { backgroundColor: destructive ? colors.error + "22" : colors.accentSoft }]}><MaterialIcons name={icon} size={20} color={tone} /></View><View style={styles.rowText}><Text style={[styles.rowLabel, { color: destructive ? colors.error : colors.foreground }]}>{label}</Text>{description ? <Text style={[styles.rowDescription, { color: colors.muted }]}>{description}</Text> : null}</View><MaterialIcons name="chevron-right" size={22} color={colors.subtle} /></Pressable>;
}

export default function AccountScreen() {
  const colors = useColors();
  const { profile, profileError, profileLoading, refreshProfile, signOut } = useChatAuth();
  const handleSignOut = () => Alert.alert("Sign out?", "You will need your email and password to sign back in.", [{ text: "Cancel", style: "cancel" }, { text: "Sign out", style: "destructive", onPress: () => void signOut().catch((error) => Alert.alert("Sign out failed", error.message)) }]);
  if (profileLoading && !profile) return <FullScreenLoader label="Loading account" />;
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><Text style={[styles.eyebrow, { color: colors.primary }]}>YOUR SPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Account</Text></View>{profile ? <View style={[styles.profileCard, { backgroundColor: colors.elevated, borderColor: colors.border }]}><Avatar profile={profile} size={70} /><View style={styles.profileMeta}><Text style={[styles.name, { color: colors.foreground }]}>{profile.display_name}</Text><View style={styles.identityLine}><InlineIdentity label={`@${profile.username}`} verified={profile.verified} textStyle={[styles.handle, { color: colors.muted }]} /><BadgeRow badges={profile.badges} /></View>{profile.bio ? <Text style={[styles.bio, { color: colors.muted }]}>{profile.bio}</Text> : null}</View></View> : <View style={[styles.errorCard, { backgroundColor: colors.error + "16", borderColor: colors.error + "55" }]}><Text style={[styles.errorTitle, { color: colors.error }]}>Profile unavailable</Text><Text style={[styles.errorText, { color: colors.muted }]}>{profileError?.message ?? "We could not load your profile details."}</Text><SecondaryButton label="Retry" onPress={() => void refreshProfile()} /></View>}<Text style={[styles.section, { color: colors.subtle }]}>PROFILE</Text><View style={[styles.sectionCard, { backgroundColor: colors.elevated, borderColor: colors.border }]}><SettingsRow icon="edit" label="Edit profile" description="Avatar, name, username, and bio" onPress={() => router.push("/edit-profile" as never)} /></View><Text style={[styles.section, { color: colors.subtle }]}>SECURITY</Text><View style={[styles.sectionCard, { backgroundColor: colors.elevated, borderColor: colors.border }]}><SettingsRow icon="lock-outline" label="Change password" description="Use a secure reset link" onPress={() => router.push("/forgot-password" as never)} /><SettingsRow icon="delete-outline" label="Request account deletion" description="Starts a secure deletion request" destructive onPress={() => router.push("/request-deletion" as never)} /></View><View style={styles.signOut}><SecondaryButton label="Sign out" destructive icon="logout" onPress={handleSignOut} /></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 40, paddingTop: 18 }, heading: { marginBottom: 4 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, title: { fontSize: 30, fontWeight: "900", letterSpacing: -0.8, marginTop: 3 }, profileCard: { alignItems: "flex-start", borderRadius: 22, borderWidth: 1, flexDirection: "row", gap: 14, padding: 16 }, profileMeta: { flex: 1 }, name: { fontSize: 19, fontWeight: "900", letterSpacing: -0.2 }, identityLine: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 }, handle: { fontSize: 14, fontWeight: "700" }, bio: { fontSize: 14, lineHeight: 20, marginTop: 10 }, section: { fontSize: 11, fontWeight: "900", letterSpacing: 1.2, marginLeft: 2, marginTop: 10 }, sectionCard: { borderRadius: 18, borderWidth: 1, overflow: "hidden" }, row: { alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 12, minHeight: 76, paddingHorizontal: 14 }, rowIcon: { alignItems: "center", borderRadius: 12, height: 40, justifyContent: "center", width: 40 }, rowText: { flex: 1 }, rowLabel: { fontSize: 15, fontWeight: "800" }, rowDescription: { fontSize: 12, lineHeight: 17, marginTop: 3 }, signOut: { marginTop: 10 }, errorCard: { borderRadius: 18, borderWidth: 1, gap: 8, padding: 16 }, errorTitle: { fontSize: 16, fontWeight: "900" }, errorText: { fontSize: 13, lineHeight: 19 } });
