import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ClayPressable, useClayStyles } from "@/components/clay-ui";
import { Avatar, EmptyState, InlineIdentity, PrimaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { createDirectConversation, listFriends } from "@/lib/chat-api";
import type { Profile } from "@/shared/chat-types";

export default function FriendsScreen() {
  const colors = useColors(); const clay = useClayStyles(); const [friends, setFriends] = useState<Profile[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { setLoading(true); const result = await listFriends(); setLoading(false); if (result.error) return setError(result.error.message); setFriends(result.data); setError(null); };
  const message = async (friend: Profile) => { const result = await createDirectConversation(friend.id); if (result.error) return setError(result.error.message); router.push({ pathname: "/conversation/[id]", params: { id: result.data, title: friend.display_name, kind: "direct", verified: friend.verified ? "true" : "false" } } as never); };
  useEffect(() => { void refresh(); }, []);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>Friends</Text><Text style={[styles.subtitle, { color: colors.muted }]}>People you know on Chat</Text></View><ClayPressable onPress={() => router.push("/find-people" as never)} radius={18} style={[styles.add, { backgroundColor: colors.accentSoft }]}><Text style={[styles.addText, { color: colors.primary }]}>Find people</Text></ClayPressable></View>{loading ? <View style={styles.loader}><ActivityIndicator color={colors.primary} /></View> : null}{error ? <EmptyState icon="cloud-off" title="Could not load friends" description={error} action={<PrimaryButton label="Retry" onPress={() => void refresh()} />} /> : null}{!loading && !error && !friends.length ? <EmptyState icon="people-outline" title="Build your circle" description="Search for people by name or username, then send a friend request." action={<PrimaryButton icon="person-add" label="Find people" onPress={() => router.push("/find-people" as never)} />} /> : null}{!loading && !error && friends.length ? <FlatList contentContainerStyle={styles.list} data={friends} keyExtractor={(item) => item.id} onRefresh={() => void refresh()} refreshing={loading} renderItem={({ item }) => <View style={[styles.friend, clay.raised, { backgroundColor: colors.elevated }]}><Pressable onPress={() => router.push(`/profile/${item.id}` as never)} style={({ pressed }) => [styles.profileTap, pressed && styles.pressed]}><Avatar profile={item} size={48} /><View style={styles.friendInfo}><InlineIdentity label={item.display_name} verified={item.verified} textStyle={[styles.name, { color: colors.foreground }]} /><Text style={[styles.handle, { color: colors.muted }]}>@{item.username}</Text></View></Pressable><ClayPressable onPress={() => void message(item)} radius={16} style={[styles.message, { backgroundColor: colors.accentSoft }]}><Text style={[styles.messageText, { color: colors.primary }]}>Message</Text></ClayPressable></View>} /> : null}</ScreenContainer>;
}

const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingBottom: 12, paddingTop: 18 }, title: { fontSize: 26, fontWeight: "900", letterSpacing: -0.5 }, subtitle: { fontSize: 14, marginTop: 5 }, add: { paddingHorizontal: 13, paddingVertical: 10 }, addText: { fontSize: 13, fontWeight: "900" }, loader: { flex: 1, justifyContent: "center" }, list: { gap: 13, paddingBottom: 24, paddingTop: 8 }, friend: { alignItems: "center", borderRadius: 24, flexDirection: "row", minHeight: 76, paddingHorizontal: 13 }, profileTap: { alignItems: "center", flex: 1, flexDirection: "row", gap: 12 }, friendInfo: { flex: 1 }, name: { fontSize: 16, fontWeight: "800" }, handle: { fontSize: 12, marginTop: 2 }, message: { paddingHorizontal: 12, paddingVertical: 9 }, messageText: { fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
