import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, View } from "react-native";

import { ClayPressable } from "@/components/clay-ui";
import { Avatar, EmptyState, InlineIdentity, PrimaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { listConversations, subscribeToConversations } from "@/lib/chat-api";
import { supabase } from "@/lib/supabase";
import { useChatAuth } from "@/providers/chat-auth-provider";
import type { ConversationSummary } from "@/shared/chat-types";

function relativeTime(value: string | null) { if (!value) return ""; const diff = Math.floor((Date.now() - new Date(value).getTime()) / 60000); if (diff < 1) return "now"; if (diff < 60) return `${diff}m`; if (diff < 1440) return `${Math.floor(diff / 60)}h`; return `${Math.floor(diff / 1440)}d`; }

export default function TextingScreen() {
  const colors = useColors();
  const { profile } = useChatAuth();
  const [conversations, setConversations] = useState<ConversationSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async (showLoading = true) => { if (showLoading) setLoading(true); const result = await listConversations(); if (showLoading) setLoading(false); if (result.error) return setError(result.error.message); setConversations(result.data); setError(null); }, []);
  useEffect(() => { void refresh(); const channel = subscribeToConversations(() => void refresh(false)); return () => { supabase.removeChannel(channel); }; }, [refresh]);
  useFocusEffect(useCallback(() => { void refresh(false); }, [refresh]));

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><View style={styles.identity}><Avatar profile={profile} size={42} /><View><Text style={[styles.eyebrow, { color: colors.primary }]}>MESSAGES</Text><Text style={[styles.title, { color: colors.foreground }]}>Texting</Text></View></View><ClayPressable onPress={() => router.push("/new-conversation" as never)} accessibilityLabel="Start a conversation" radius={18} style={[styles.compose, { backgroundColor: colors.primary }]}><View style={styles.composeContent}><MaterialIcons name="edit-square" color={colors.onPrimary} size={22} /></View></ClayPressable></View>{loading ? <View style={styles.loader}><ActivityIndicator color={colors.primary} /></View> : null}{error ? <EmptyState icon="cloud-off" title="Could not load conversations" description={error} action={<PrimaryButton label="Retry" onPress={() => void refresh()} />} /> : null}{!loading && !error && !conversations.length ? <EmptyState icon="forum" title="Your conversations will appear here" description="Start a private conversation with a friend or create a group to begin." action={<PrimaryButton icon="add" label="New conversation" onPress={() => router.push("/new-conversation" as never)} />} /> : null}{!loading && !error && conversations.length ? <FlatList data={conversations} contentContainerStyle={styles.list} keyExtractor={(item) => item.id} refreshing={loading} onRefresh={() => void refresh()} renderItem={({ item }) => <ClayPressable onPress={() => router.push({ pathname: "/conversation/[id]", params: { id: item.id, title: item.title, kind: item.kind, verified: item.verified ? "true" : "false" } } as never)} radius={24} style={[styles.row, { backgroundColor: colors.elevated }]}><View style={styles.rowContent}><Avatar profile={{ display_name: item.title, avatar_path: item.avatar_path }} size={52} /><View style={styles.rowBody}><View style={styles.rowTop}><View style={styles.conversationTitle}><InlineIdentity label={item.title} verified={item.kind === "direct" && item.verified} textStyle={[styles.conversationName, { color: colors.foreground }]} />{item.kind === "group" ? <MaterialIcons name="groups" size={15} color={colors.primary} /> : null}</View><Text style={[styles.time, { color: colors.subtle }]}>{relativeTime(item.last_message_at)}</Text></View><View style={styles.previewRow}><Text numberOfLines={1} style={[styles.preview, { color: colors.muted }, item.unread_count > 0 && { color: colors.foreground, fontWeight: "700" }]}>{item.last_message?.body || (item.last_message?.attachments?.length ? "Attachment" : "No messages yet")}</Text>{item.unread_count > 0 ? <View style={[styles.unread, { backgroundColor: colors.primary }]}><Text style={[styles.unreadText, { color: colors.onPrimary }]}>{item.unread_count > 99 ? "99+" : item.unread_count}</Text></View> : null}</View></View></View></ClayPressable>} /> : null}</ScreenContainer>;
}

const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingBottom: 16, paddingTop: 18 }, identity: { alignItems: "center", flexDirection: "row", gap: 11 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 28, fontWeight: "900", letterSpacing: -0.7, marginTop: 1 }, compose: { height: 48, width: 48 }, composeContent: { alignItems: "center", height: 48, justifyContent: "center", width: 48 }, loader: { flex: 1, justifyContent: "center" }, list: { gap: 13, paddingBottom: 30 }, row: { minHeight: 82, paddingHorizontal: 14, paddingVertical: 13 }, rowContent: { alignItems: "center", flexDirection: "row", gap: 12, minHeight: 56 }, rowBody: { flex: 1, gap: 6 }, rowTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, conversationTitle: { alignItems: "center", flex: 1, flexDirection: "row", gap: 5 }, conversationName: { flexShrink: 1, fontSize: 16, fontWeight: "800" }, time: { fontSize: 12, marginLeft: 8 }, previewRow: { alignItems: "center", flexDirection: "row", gap: 8 }, preview: { flex: 1, fontSize: 13 }, unread: { alignItems: "center", borderRadius: 12, justifyContent: "center", minWidth: 22, paddingHorizontal: 6, paddingVertical: 3 }, unreadText: { fontSize: 10, fontWeight: "900" } });
