import { useEffect, useState } from "react";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, StyleSheet, Text, View } from "react-native";

import { ClayPressable } from "@/components/clay-ui";
import { Avatar, EmptyState, PrimaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { listNotifications, markNotificationRead, respondToFriendRequest, respondToGroupInvite } from "@/lib/chat-api";
import { useChatAuth } from "@/providers/chat-auth-provider";
import type { AppNotification } from "@/shared/chat-types";

export default function NotificationsScreen() {
  const colors = useColors(); const { refreshUnreadCounts } = useChatAuth(); const [notifications, setNotifications] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { setLoading(true); const result = await listNotifications(); setLoading(false); if (result.error) return setError(result.error.message); setNotifications(result.data); setError(null); };
  const respond = async (notification: AppNotification, accept: boolean) => { const identifier = notification.kind === "friend_request" ? notification.data.friend_request_id : notification.data.group_invite_id; if (!identifier) return; const result = notification.kind === "friend_request" ? await respondToFriendRequest(identifier, accept) : await respondToGroupInvite(identifier, accept); if (result.error) setError(result.error.message); else { if (!accept) await markNotificationRead(notification.id); void refresh(); void refreshUnreadCounts(); } };
  const open = (notification: AppNotification) => { if (notification.kind === "group_invite" && notification.data.group_invite_id) { router.push(`/group-invitation/${notification.data.group_invite_id}` as never); return; } void markNotificationRead(notification.id); void refreshUnreadCounts(); };
  useEffect(() => { void refresh(); void refreshUnreadCounts(); }, [refreshUnreadCounts]);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><Text style={[styles.title, { color: colors.foreground }]}>Notifications</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Requests, invitations, and activity</Text></View>{loading ? <View style={styles.loader}><ActivityIndicator color={colors.primary} /></View> : null}{error ? <EmptyState icon="cloud-off" title="Could not load notifications" description={error} action={<PrimaryButton label="Retry" onPress={() => void refresh()} />} /> : null}{!loading && !error && !notifications.length ? <EmptyState icon="notifications-none" title="You are all caught up" description="Friend requests, group invitations, and relevant activity will show up here." /> : null}{!loading && !error && notifications.length ? <FlatList data={notifications} contentContainerStyle={styles.list} keyExtractor={(item) => item.id} onRefresh={() => void refresh()} refreshing={loading} renderItem={({ item }) => <ClayPressable onPress={() => open(item)} radius={24} style={[styles.notification, { backgroundColor: item.read_at ? colors.elevated : colors.accentSoft }]}><View style={styles.notificationContent}><Avatar profile={item.actor ? { avatar_path: item.actor.avatar_path, display_name: item.actor.display_name } : null} size={40} /><View style={styles.body}><Text style={[styles.itemTitle, { color: colors.foreground }]}>{item.kind === "friend_request" && item.actor?.display_name ? `${item.actor.display_name} sent you a friend request` : item.title}</Text>{item.body ? <Text style={[styles.itemBody, { color: colors.muted }]}>{item.kind === "group_invite" ? `${item.body} Tap to view the group.` : item.body}</Text> : null}{item.kind === "friend_request" && !item.read_at ? <View style={styles.actions}><ClayPressable onPress={() => void respond(item, true)} radius={16} style={[styles.accept, { backgroundColor: colors.primary }]}><Text style={[styles.acceptText, { color: colors.onPrimary }]}>Accept</Text></ClayPressable><ClayPressable onPress={() => void respond(item, false)} radius={16} style={[styles.decline, { backgroundColor: colors.elevated }]}><Text style={[styles.declineText, { color: colors.foreground }]}>Decline</Text></ClayPressable></View> : null}</View></View></ClayPressable>} /> : null}</ScreenContainer>;
}

const styles = StyleSheet.create({ header: { paddingBottom: 12, paddingTop: 18 }, title: { fontSize: 26, fontWeight: "900", letterSpacing: -0.5 }, subtitle: { fontSize: 14, marginTop: 5 }, loader: { flex: 1, justifyContent: "center" }, list: { gap: 13, paddingBottom: 24, paddingTop: 8 }, notification: { minHeight: 78, padding: 14 }, notificationContent: { alignItems: "flex-start", flexDirection: "row", gap: 11 }, body: { flex: 1 }, itemTitle: { fontSize: 14, fontWeight: "800" }, itemBody: { fontSize: 13, lineHeight: 18, marginTop: 3 }, actions: { flexDirection: "row", gap: 9, marginTop: 11 }, accept: { paddingHorizontal: 12, paddingVertical: 8 }, acceptText: { fontSize: 12, fontWeight: "900" }, decline: { paddingHorizontal: 12, paddingVertical: 8 }, declineText: { fontSize: 12, fontWeight: "900" } });
