import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Avatar, EmptyState, PrimaryButton } from "@/components/chat-ui";
import { ScreenContainer } from "@/components/screen-container";
import { listNotifications, markNotificationRead, respondToFriendRequest, respondToGroupInvite } from "@/lib/chat-api";
import type { AppNotification } from "@/shared/chat-types";

export default function NotificationsScreen() {
  const [notifications, setNotifications] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { setLoading(true); const result = await listNotifications(); setLoading(false); if (result.error) return setError(result.error.message); setNotifications(result.data); setError(null); };
  const respond = async (notification: AppNotification, accept: boolean) => { const identifier = notification.kind === "friend_request" ? notification.data.friend_request_id : notification.data.group_invite_id; if (!identifier) return; const result = notification.kind === "friend_request" ? await respondToFriendRequest(identifier, accept) : await respondToGroupInvite(identifier, accept); if (result.error) setError(result.error.message); else { await markNotificationRead(notification.id); void refresh(); } };
  useEffect(() => { void refresh(); }, []);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><Text style={styles.title}>Notifications</Text><Text style={styles.subtitle}>Requests, invitations, and activity</Text></View>{loading ? <View style={styles.loader}><ActivityIndicator color="#3858E9" /></View> : null}{error ? <EmptyState icon="cloud-off" title="Could not load notifications" description={error} action={<PrimaryButton label="Retry" onPress={() => void refresh()} />} /> : null}{!loading && !error && !notifications.length ? <EmptyState icon="notifications-none" title="You are all caught up" description="Friend requests, group invitations, and relevant activity will show up here." /> : null}{!loading && !error && notifications.length ? <FlatList data={notifications} contentContainerStyle={styles.list} keyExtractor={(item) => item.id} onRefresh={() => void refresh()} refreshing={loading} renderItem={({ item }) => <Pressable onPress={() => void markNotificationRead(item.id)} style={({ pressed }) => [styles.notification, !item.read_at && styles.unread, pressed && styles.pressed]}><Avatar profile={item.actor ? { avatar_path: item.actor.avatar_path, display_name: item.actor.display_name } : null} size={40} /><View style={styles.body}><Text style={styles.itemTitle}>{item.title}</Text>{item.body ? <Text style={styles.itemBody}>{item.body}</Text> : null}{(item.kind === "friend_request" || item.kind === "group_invite") && !item.read_at ? <View style={styles.actions}><Pressable onPress={() => void respond(item, true)} style={styles.accept}><Text style={styles.acceptText}>Accept</Text></Pressable><Pressable onPress={() => void respond(item, false)} style={styles.decline}><Text style={styles.declineText}>Decline</Text></Pressable></View> : null}</View></Pressable>} /> : null}</ScreenContainer>;
}
const styles = StyleSheet.create({ header: { paddingTop: 15 }, title: { color: "#171B25", fontSize: 26, fontWeight: "900", letterSpacing: -0.5 }, subtitle: { color: "#687086", fontSize: 14, marginTop: 5 }, loader: { flex: 1, justifyContent: "center" }, list: { paddingBottom: 20, paddingTop: 12 }, notification: { alignItems: "flex-start", borderBottomColor: "#E9ECF3", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 10, minHeight: 72, paddingVertical: 12 }, unread: { backgroundColor: "#F4F6FF", marginHorizontal: -5, paddingHorizontal: 5 }, body: { flex: 1 }, itemTitle: { color: "#202738", fontSize: 14, fontWeight: "800" }, itemBody: { color: "#687086", fontSize: 13, lineHeight: 18, marginTop: 3 }, actions: { flexDirection: "row", gap: 8, marginTop: 10 }, accept: { backgroundColor: "#3858E9", borderRadius: 9, paddingHorizontal: 11, paddingVertical: 7 }, acceptText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, decline: { borderColor: "#DCE1ED", borderRadius: 9, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, declineText: { color: "#687086", fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.72 } });
