import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Clipboard from "expo-clipboard";
import * as DocumentPicker from "expo-document-picker";
import * as ImagePicker from "expo-image-picker";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, FullScreenLoader, InlineIdentity } from "@/components/chat-ui";
import { MessageAttachmentCard } from "@/components/message-attachment";
import { ScreenContainer } from "@/components/screen-container";
import { VoiceRecorderButton } from "@/components/voice-recorder-button";
import { deleteMessage, editMessage, listMessages, markConversationRead, reportMessage, sendAttachment, sendMessage, subscribeToConversation, toggleReaction } from "@/lib/chat-api";
import { useChatAuth } from "@/providers/chat-auth-provider";
import type { ChatMessage, PendingAttachment } from "@/shared/chat-types";

function MessageBubble({ message, mine, group, onLongPress, onReply, onReact }: { message: ChatMessage; mine: boolean; group: boolean; onLongPress: () => void; onReply: () => void; onReact: () => void }) {
  return <Pressable delayLongPress={350} onLongPress={onLongPress} style={[styles.messageRow, mine && styles.mineRow]}><>{!mine ? <Avatar profile={message.sender ?? null} size={32} /> : null}<View style={[styles.messageWrap, mine && styles.mineWrap]}>{!mine && group ? <Text style={styles.senderName}>{message.sender?.display_name ?? "Member"}</Text> : null}<View style={[styles.bubble, mine ? styles.mineBubble : styles.otherBubble]}>{message.body ? <Text style={[styles.messageText, mine && styles.mineText]}>{message.body}</Text> : null}{message.attachments?.map((attachment) => <View key={attachment.id} style={message.body ? styles.attachmentSpacing : undefined}><MessageAttachmentCard attachment={attachment} mine={mine} /></View>)}<Text style={[styles.messageTime, mine && styles.mineTime]}>{new Date(message.created_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}{message.edited_at ? " · edited" : ""}</Text></View>{message.reactions?.length ? <Pressable onPress={onReact} style={styles.reaction}><Text>{message.reactions[0].emoji}</Text><Text style={styles.reactionText}>{message.reactions.length}</Text></Pressable> : <Pressable onPress={onReact} style={styles.quickReact}><Text>+</Text></Pressable>}<Pressable onPress={onReply} style={styles.replyButton}><MaterialIcons name="reply" size={15} color={mine ? "#E7EBFF" : "#687086"} /></Pressable></View></></Pressable>;
}

export default function ConversationScreen() {
  const { id, title = "Conversation", kind = "direct", verified = "false" } = useLocalSearchParams<{ id: string; title?: string; kind?: "direct" | "group"; verified?: string }>(); const { profile } = useChatAuth(); const [messages, setMessages] = useState<ChatMessage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [draft, setDraft] = useState(""); const [replyingTo, setReplyingTo] = useState<ChatMessage | null>(null); const [editing, setEditing] = useState<ChatMessage | null>(null); const [sending, setSending] = useState(false); const listRef = useRef<FlatList<ChatMessage>>(null);
  const refresh = useCallback(async () => { const result = await listMessages(id); if (result.error) { setError(result.error.message); } else { setMessages(result.data); setError(null); } setLoading(false); void markConversationRead(id); }, [id]);
  useEffect(() => { void refresh(); const channel = subscribeToConversation(id, () => void refresh()); return () => { channel.unsubscribe(); }; }, [id, refresh]);
  const submit = async () => { if (!draft.trim()) return; setSending(true); const result = editing ? await editMessage(editing.id, draft) : await sendMessage(id, draft, replyingTo?.id); setSending(false); if (result.error) return Alert.alert("Message not sent", result.error.message); setDraft(""); setReplyingTo(null); setEditing(null); void refresh(); };
  const chooseMedia = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.All, quality: 0.9, selectionLimit: 1 }); if (result.canceled) return; const asset = result.assets[0]; if ((asset.fileSize ?? 0) > 100 * 1024 * 1024) return Alert.alert("File too large", "Attachments must be 100 MB or smaller."); const item: PendingAttachment = { uri: asset.uri, name: asset.fileName ?? `media-${Date.now()}`, mimeType: asset.mimeType ?? (asset.type === "video" ? "video/mp4" : "image/jpeg"), size: asset.fileSize ?? 1, kind: asset.type === "video" ? "video" : "image", width: asset.width, height: asset.height }; void uploadAttachment(item); };
  const chooseFile = async () => { const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; if ((asset.size ?? 0) > 100 * 1024 * 1024) return Alert.alert("File too large", "Attachments must be 100 MB or smaller."); const item: PendingAttachment = { uri: asset.uri, name: asset.name, mimeType: asset.mimeType ?? "application/octet-stream", size: asset.size ?? 1, kind: "file" }; void uploadAttachment(item); };
  const uploadAttachment = async (attachment: PendingAttachment) => { setSending(true); const result = await sendAttachment(id, attachment, draft); setSending(false); if (result.error) return Alert.alert("Attachment not sent", result.error.message); setDraft(""); void refresh(); };
  const attachmentMenu = () => Alert.alert("Attach", "Choose an item to send.", [{ text: "Photo or video", onPress: () => void chooseMedia() }, { text: "File", onPress: () => void chooseFile() }, { text: "Cancel", style: "cancel" }]);
  const messageMenu = (message: ChatMessage) => { const actions: any[] = []; if (message.body) actions.push({ text: "Copy text", onPress: () => void Clipboard.setStringAsync(message.body ?? "") }); actions.push({ text: "Reply", onPress: () => { setReplyingTo(message); setEditing(null); } }, { text: "React 👍", onPress: async () => { const active = message.reactions?.some((reaction) => reaction.user_id === profile?.id && reaction.emoji === "👍") ?? false; const result = await toggleReaction(message.id, "👍", active); if (result.error) Alert.alert("Reaction unavailable", result.error.message); else void refresh(); } }); if (message.sender_id === profile?.id && message.body) actions.push({ text: "Edit", onPress: () => { setEditing(message); setDraft(message.body ?? ""); setReplyingTo(null); } }, { text: "Delete", style: "destructive", onPress: async () => { const result = await deleteMessage(message.id); if (result.error) Alert.alert("Delete unavailable", result.error.message); else void refresh(); } }); else actions.push({ text: "Report message", style: "destructive", onPress: async () => { const result = await reportMessage(message.id); if (result.error) Alert.alert("Report unavailable", result.error.message); else Alert.alert("Report submitted", "Thank you. Your report was recorded securely."); } }); actions.push({ text: "Cancel", style: "cancel" }); Alert.alert("Message actions", undefined, actions); };
  if (loading) return <FullScreenLoader label="Loading conversation" />;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={styles.grow}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.headerButton}><MaterialIcons name="arrow-back" size={24} color="#171B25" /></Pressable><View style={styles.headerTitle}><InlineIdentity label={title} verified={kind === "direct" && verified === "true"} textStyle={styles.title} /><Text style={styles.subtitle}>{kind === "group" ? "Group conversation" : "Private conversation"}</Text></View><Pressable onPress={() => kind === "group" ? router.push(`/group/${id}` as never) : router.push(`/call/${id}?mode=video&title=${encodeURIComponent(title)}` as never)} style={styles.headerButton}><MaterialIcons name={kind === "group" ? "groups" : "videocam"} size={24} color="#3858E9" /></Pressable></View>{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void refresh()}><Text style={styles.retry}>Retry</Text></Pressable></View> : null}<FlatList ref={listRef} data={messages} contentContainerStyle={styles.messages} keyExtractor={(item) => item.id} onContentSizeChange={() => listRef.current?.scrollToEnd({ animated: false })} renderItem={({ item }) => <MessageBubble message={item} mine={item.sender_id === profile?.id} group={kind === "group"} onLongPress={() => messageMenu(item)} onReply={() => { setReplyingTo(item); setEditing(null); }} onReact={() => void toggleReaction(item.id, "👍", Boolean(item.reactions?.some((reaction) => reaction.user_id === profile?.id && reaction.emoji === "👍"))).then(() => void refresh())} />} ListEmptyComponent={<Text style={styles.empty}>No messages yet. Say hello.</Text>} />{replyingTo || editing ? <View style={styles.context}><MaterialIcons name={editing ? "edit" : "reply"} color="#3858E9" size={17} /><Text numberOfLines={1} style={styles.contextText}>{editing ? "Editing your message" : `Replying to ${replyingTo?.sender?.display_name ?? "message"}`}</Text><Pressable onPress={() => { setReplyingTo(null); setEditing(null); setDraft(""); }}><MaterialIcons name="close" color="#687086" size={20} /></Pressable></View> : null}<View style={styles.composer}><Pressable onPress={attachmentMenu} disabled={sending} style={styles.attach}><MaterialIcons name="add" color="#3858E9" size={25} /></Pressable><VoiceRecorderButton disabled={sending} onRecorded={uploadAttachment} /><TextInput multiline onChangeText={setDraft} placeholder="Message" placeholderTextColor="#8A93A7" style={styles.composerInput} value={draft} /><Pressable onPress={() => void submit()} disabled={sending || !draft.trim()} style={({ pressed }) => [styles.send, (!draft.trim() || sending) && styles.sendDisabled, pressed && styles.pressed]}>{sending ? <ActivityIndicator color="#FFFFFF" size="small" /> : <MaterialIcons name="send" color="#FFFFFF" size={20} />}</Pressable></View></KeyboardAvoidingView></ScreenContainer>;
}

const styles = StyleSheet.create({ grow: { flex: 1 }, header: { alignItems: "center", borderBottomColor: "#E4E7EF", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 58, paddingHorizontal: 8 }, headerButton: { alignItems: "center", height: 44, justifyContent: "center", width: 44 }, headerTitle: { flex: 1 }, title: { color: "#171B25", fontSize: 16, fontWeight: "900" }, subtitle: { color: "#7C8497", fontSize: 11, marginTop: 2 }, messages: { gap: 9, padding: 14, paddingBottom: 18 }, empty: { color: "#7C8497", marginTop: 35, textAlign: "center" }, messageRow: { alignItems: "flex-end", alignSelf: "flex-start", flexDirection: "row", gap: 7, maxWidth: "88%" }, mineRow: { alignSelf: "flex-end" }, messageWrap: { gap: 3, maxWidth: "100%" }, mineWrap: { alignItems: "flex-end" }, senderName: { color: "#687086", fontSize: 11, fontWeight: "800", marginLeft: 2 }, bubble: { borderRadius: 18, maxWidth: "100%", padding: 11 }, otherBubble: { backgroundColor: "#FFFFFF", borderColor: "#E4E7EF", borderWidth: 1, borderBottomLeftRadius: 5 }, mineBubble: { backgroundColor: "#3858E9", borderBottomRightRadius: 5 }, messageText: { color: "#202738", fontSize: 15, lineHeight: 21 }, mineText: { color: "#FFFFFF" }, messageTime: { color: "#7C8497", fontSize: 10, marginTop: 5 }, mineTime: { color: "#DDE3FF" }, attachmentSpacing: { marginTop: 8 }, reaction: { alignItems: "center", alignSelf: "flex-start", backgroundColor: "#FFFFFF", borderColor: "#E4E7EF", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 4, marginTop: 3, paddingHorizontal: 7, paddingVertical: 3 }, reactionText: { color: "#687086", fontSize: 11 }, quickReact: { alignItems: "center", backgroundColor: "#F0F2F8", borderRadius: 10, height: 20, justifyContent: "center", width: 20 }, replyButton: { alignItems: "center", height: 24, justifyContent: "center", width: 24 }, context: { alignItems: "center", backgroundColor: "#EFF2FF", borderTopColor: "#DDE3FF", borderTopWidth: 1, flexDirection: "row", gap: 8, paddingHorizontal: 16, paddingVertical: 8 }, contextText: { color: "#3858E9", flex: 1, fontSize: 12, fontWeight: "700" }, composer: { alignItems: "flex-end", backgroundColor: "#FFFFFF", borderTopColor: "#E4E7EF", borderTopWidth: 1, flexDirection: "row", gap: 8, padding: 10 }, attach: { alignItems: "center", height: 42, justifyContent: "center", width: 34 }, composerInput: { backgroundColor: "#F3F5F9", borderRadius: 20, color: "#171B25", flex: 1, fontSize: 15, maxHeight: 110, minHeight: 42, paddingHorizontal: 14, paddingTop: 11 }, send: { alignItems: "center", backgroundColor: "#3858E9", borderRadius: 21, height: 42, justifyContent: "center", width: 42 }, sendDisabled: { backgroundColor: "#AAB5E8" }, pressed: { opacity: 0.8 }, error: { alignItems: "center", backgroundColor: "#FDF0F0", flexDirection: "row", gap: 9, padding: 9 }, errorText: { color: "#B52D2D", flex: 1, fontSize: 12 }, retry: { color: "#B52D2D", fontSize: 12, fontWeight: "900" } });
